create table ts6.issue (id  serial not null unique, datecreated timestamp not null, fdel int4 not null, issue_id int4, level int4 not null, name varchar(255) not null, version timestamp not null, workgroup_id int4 not null, primary key (id), unique (level, name, workgroup_id, fdel));
create table ts6.loginLog (id  bigserial not null unique, userAgent_id int4, bsuccess bool not null, dateLogin timestamp not null, dateLogout timestamp, remoteAddress varchar(1024), remoteHost varchar(1024), sessionId varchar(255) unique, username varchar(45), userpassword varchar(45), userScreen_id int4, user_id int4, primary key (id));
create table ts6.timesheet (id  bigserial not null unique, comment varchar(255), datecreated timestamp not null, datetimefrom timestamp not null, datetimetill timestamp, fdel int4 not null, issue_id int4, version timestamp not null, user_id int4 not null, primary key (id), unique (user_id, datetimefrom));
create table ts6.token (id  serial not null unique, action_id int4 not null, dateaccepted timestamp, datecreated timestamp not null, daterejected timestamp, properties varchar(255), token varchar(127) not null, version timestamp not null, user_id int4, primary key (id));
create table ts6.user1 (id  serial not null unique, bactive bool, birthday timestamp, birthyear int4, bsticky bool, city varchar(45), company varchar(45), country_iso varchar(3), datTerms timestamp, datecreated timestamp not null, email varchar(255), fdel int4 not null, firstname varchar(45), name varchar(45), newemail varchar(255), newpassword varchar(45), role_id int4, username varchar(45), userpassword varchar(45), version timestamp not null, zip varchar(12), confirming_user_id int4, parent_user_id int4, primary key (id), unique (email, fdel), unique (username, fdel));
create table ts6.userAgent (id  serial not null unique, name varchar(64), userAgent varchar(2048) not null, primary key (id), unique (userAgent));
create table ts6.userScreen (id  serial not null unique, name varchar(64), screenResolution varchar(2048), sixeX int4, sixeY int4, primary key (id), unique (screenResolution));
create table ts6.userinvitation (userhost_id int4 not null, userinvited_id int4 not null, baccepted bool, datetime_invitation timestamp, datetime_response timestamp, primary key (userhost_id, userinvited_id));
create table ts6.userworkgroup (user_id int4 not null, workgroup_id int4 not null, primary key (user_id, workgroup_id));
create table ts6.version (id  serial not null unique, dateTime timestamp not null, topic varchar(16) not null, version varchar(16) not null, primary key (id));
create table ts6.workgroup (id  serial not null unique, datecreated timestamp not null, fdel int4 not null, name varchar(255), owner_id int4, version timestamp not null, primary key (id), unique (name, owner_id, fdel));
alter table ts6.issue add constraint fk_issue_workgroup foreign key (workgroup_id) references ts6.workgroup;
alter table ts6.issue add constraint fk_issue_parentIssue foreign key (issue_id) references ts6.issue;
create index loginLogIndex on ts6.loginLog (user_id, dateLogin);
alter table ts6.loginLog add constraint fk_loginLog_userScreen foreign key (userScreen_id) references ts6.userScreen;
alter table ts6.loginLog add constraint fk_loginLog_user foreign key (user_id) references ts6.user1;
alter table ts6.loginLog add constraint fk_loginLog_userAgent foreign key (userAgent_id) references ts6.userAgent;
alter table ts6.timesheet add constraint fk_timesheet_user foreign key (user_id) references ts6.user1;
alter table ts6.timesheet add constraint fk_timesheet_issue foreign key (issue_id) references ts6.issue;
create index tokenIndex on ts6.token (token);
alter table ts6.token add constraint fk_token_user foreign key (user_id) references ts6.user1;
alter table ts6.user1 add constraint fk_user_confirmingUser foreign key (confirming_user_id) references ts6.user1;
alter table ts6.user1 add constraint fk_user_parentUser foreign key (parent_user_id) references ts6.user1;
alter table ts6.userinvitation add constraint fk_userInvitation_userHost foreign key (userhost_id) references ts6.user1;
alter table ts6.userinvitation add constraint fk_userInvitation_userInvited foreign key (userinvited_id) references ts6.user1;
alter table ts6.userworkgroup add constraint fk_userWorkgroup_workgroup foreign key (workgroup_id) references ts6.workgroup;
alter table ts6.userworkgroup add constraint fk_userWorkgroup_user foreign key (user_id) references ts6.user1;
alter table ts6.workgroup add constraint fk_workgroup_user foreign key (owner_id) references ts6.user1;
